[project]
name = "general-polymarket-bots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.1",
    "py-clob-client>=0.34.5",
    "requests>=2.32.5",
]
